# ----------------------- #
#      Main Configs       #
# ----------------------- #

name:    Mapping Laws
url:     'https://watershedlegal.github.io/mapping-laws/'
author:
  name:  'Watershed Legal Services, PLLC'
  email: caseykuhlman@watershedlegal.com
exclude: [".gitignore", ".ruby-version", ".ruby-gemset", "Gemfile", "Gemfile.lock", "countries_data_parser.rb", "README.md", "Rakefile"]

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

root:            "/"
permalink:       "countries/:title.html"
destination:     "_site"
safe:            true
lsi:             false
pygments:        false
markdown:        redcarpet
titlecase:       true
